lon: -63.2594986
lat: 50.6538010
proxy_stations: [Reservoir,Bernard_lake,Foret_ouest,Foret_est]
radiation: False
precipitation: True
energy_balance: False
friction_vel: 
    vars: []
    temperature_var: 
flux_vars: []
strg_vars: []
grnd_vars: []
carbon_vars: []
