lon: -63.4051018
lat: 50.9020996
proxy_stations: [Foret_est,Bernard_lake,Berge,Reservoir]
station_type: land
radiation: False
precipitation: False
energy_balance: False
friction_vel: 
    vars: []
    temperature_var: 
flux_vars: [LE_corr,H_corr]
strg_vars: []
grnd_vars: []
carbon_vars: []
