lon: -63.2594986
lat: 50.6538010
proxy_stations: [Reservoir,Foret_ouest,Foret_est]
radiation: False
energy_balance: False
friction_vel: 
    vars: []
    temperature_var: 
flux_vars: [LE_corr,H_corr]
strg_vars: []
grnd_vars: []
carbon_vars: []
