meta:
    site: For forested sites
    name: Marginal distribution sampling (MDS)
    reference: "Reichstein. (2005). On the separation of net ecosystem exchange into assimilation and ecosystem respiration: review and improved algorithm. Global Change Biology, 11(9), 1424–1439. https://doi.org/info:doi/
    CO2 and CH4 variable proxys (short wave down, air temperature, soil temperature vapor pressure deficit)
    - Songyan Zhu, Jon McCalmont, Laura M. Cardenas, Andrew M. Cunliffe, Louise Olde, Caroline Signori-Müller, Marcy E. Litvak, Timothy Hill, Gap-filling carbon dioxide, water, energy, and methane fluxes in challenging ecosystems; Comparing between methods, drivers, and gap-lengths, Agricultural and Forest Meteorology, Volume 332, 2023, 109365, ISSN 0168-1923
    - Yu, B.; Xu, W.; Yan, L.;Bao, H.; Yu, H. Spatial and Temporal Variability and Driving Factors of Carbon Dioxide and Nitrous Oxide Fluxes in Alpine Wetland Ecosystems. Plants 2022, 11, 2823. https:// doi.org/10.3390/plants11212823"

vars_to_fill:

    LE:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CO2_flux:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            soil_temp_CS650_1: 2.5
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CH4_flux:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            soil_temp_CS650_1: 2.5
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50
    
    LE_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CO2_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            soil_temp_CS650_1: 2.5
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CH4_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            soil_temp_CS650_1: 2.5
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    LE_corr:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H_corr:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp_HMP45C: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50