meta:
    site: For forested sites
    name: Marginal distribution sampling (MDS)
    reference: "Reichstein. (2005). On the separation of net ecosystem exchange into assimilation and ecosystem respiration: review and improved algorithm. Global Change Biology, 11(9), 1424–1439. https://doi.org/info:doi/"

vars_to_fill:

    LE:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CO2_flux:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CH4_flux:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50
    
    LE_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CO2_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    CH4_strg:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    LE_corr:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50

    H_corr:
        proxy_vars:
            rad_shortwave_down_CNR4: 50
            air_temp: 2.5
            air_vpd: 500
        proxy_vars_subset:
            rad_shortwave_down_CNR4: 50