meta:
    site: For water sites
    name: Marginal distribution sampling (MDS)
    reference: "Reichstein. (2005). On the separation of net ecosystem exchange into assimilation and ecosystem respiration: review and improved algorithm. Global Change Biology, 11(9), 1424–1439. https://doi.org/info:doi/"

vars_to_fill:

    LE:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    H:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    CO2_flux:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    CH4_flux:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5
    
    LE_strg:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    H_strg:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    CO2_strg:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    CH4_strg:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    LE_corr:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5

    H_corr:
        proxy_vars:
            delta_temp_air_eau: 3.5
            wind_speed_05103: 1
            air_relhum_HMP45C: 5
        proxy_vars_subset:
            delta_temp_air_eau: 3.5