dataset:
    'name': 'reanalysis-era5-single-levels'
    'short_name': 'ERA5'
    'product_type': 'reanalysis'
bounding_rectangle: [53, -64.7, 50.2, -62.4 ] # North, West, South, East.
variables: [
    # Atmospheric variables
    'boundary_layer_height'
    ]