era5:
    dataset:
        'name': 'reanalysis-era5-single-levels'
        'short_name': 'ERA5'
        'product_type': 'reanalysis'
    bounding_rectangle: [48, -72, 46,-70 ] # North, West, South, East.
    variables: [
        # Atmospheric variables
        'boundary_layer_height'
        ]
era5-land:
    dataset:
        'name': 'reanalysis-era5-land'
        'short_name': 'ERA5L'
        'product_type': 'reanalysis'
    bounding_rectangle: [48, -72, 46,-70 ] # North, West, South, East.
    variables: [
        # Lake variables
        'lake_mix_layer_temperature',
        # Snow variables
        'snow_cover',
        'snow_density',
        'snow_depth',
        'snow_depth_water_equivalent',
        'snowmelt',
        # Standard meteorological variables
        '10m_u_component_of_wind',
        '10m_v_component_of_wind',
        '2m_temperature',
        '2m_dewpoint_temperature',
        'skin_temperature',
        'soil_temperature_level_1',
        'soil_temperature_level_2',
        'volumetric_soil_water_layer_1',
        'volumetric_soil_water_layer_2',
        'snowfall',
        'surface_solar_radiation_downwards',
        'surface_thermal_radiation_downwards',
        'surface_net_solar_radiation',
        'surface_net_thermal_radiation',
        'surface_pressure',
        'total_precipitation',
        # Fluxes
        'surface_sensible_heat_flux',
        'surface_latent_heat_flux',
        'total_evaporation',
        'potential_evaporation',
        'evaporation_from_open_water_surfaces_excluding_oceans',
        'evaporation_from_vegetation_transpiration'
        ]